server:
  port: 8008
spring:
  application:
    name: spring-cloud-eureka
eureka:
  instance:
    hostname: peer3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8007/eureka/