eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
spring:
  application:
    name: spring-cloud-base
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  mvc:
    view:
      suffix: .html
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.dms.bootapp.domain
