bootapp:
  appName: Spring Cloud Base Model
  appVersion: 1.0.0
  companyCode: QM_DMS
server:
  session-timeout: 3000
  tomcat:
    max-threads: 20
    min-spare-threads: 2
  port: 8201
  max-http-header-size: 102400
logging:
  level:
    root: info
    com.dms.bootapp.dao: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.133.80.214:3306/bootapp_cloud?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: dms_5906928
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
ftp:
  FTP_ADDRESS: 10.133.92.245
  FTP_PORT: 8082
  FTP_USERNAME: qm_app
  FTP_PASSWORD: dms_5906928
  TOMCAT_POST: 8081
  FTP_PATH: scap_img
  FTP_HOST: 10.133.92.245